package main

import (
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func generateOne(t *testing.T, filename string, src []byte, allow map[string]bool) (string, []byte, map[string]bool) {
	t.Helper()
	files, found, err := generate(filename, src, allow)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if len(files) == 0 {
		return "", nil, found
	}
	return files[0].path, files[0].data, found
}

func TestGenerate(t *testing.T) {
	in := `package p

type S struct {
	// desc=Tunnel identifier
	Name string ` + tag(`toml:"name"`) + `
}

type Other struct {
	// desc=should not appear
	Skip int ` + tag(`toml:"skip"`) + `
}
`
	path, out, found := generateOne(t, "t.go", []byte(in), toSet([]string{"S"}))
	if !strings.HasSuffix(path, "zfielddocs_S.go") {
		t.Fatalf("path = %q", path)
	}
	if !found["S"] {
		t.Fatal("expected S to be found")
	}
	if found["Other"] {
		t.Fatal("did not expect Other to be found")
	}
	want := formatted(t, `// Code generated by gen_struct_tags; DO NOT EDIT.

package p

import "github.com/riraccuia/pig/pkg/common"

func (S) DescribeFields() map[string]common.FieldMeta {
	return map[string]common.FieldMeta{
		"name": {Desc: "Tunnel identifier"},
	}
}
`)
	if string(out) != want {
		t.Fatalf("output mismatch\ngot:\n%s\nwant:\n%s", out, want)
	}
}

func TestGenerateRecursive(t *testing.T) {
	in := `package p

type Root struct {
	// desc=logging
	Log Log ` + tag(`toml:"log"`) + `
	// desc=tunnels
	Tunnels []Tun ` + tag(`toml:"tunnels"`) + `
}

type Log struct {
	// desc=path to log
	File string ` + tag(`toml:"file"`) + `
}

type Tun struct {
	// desc=tunnel id
	Name string ` + tag(`toml:"name"`) + `
}

type Other struct {
	// desc=skip me
	X int ` + tag(`toml:"x"`) + `
}
`
	_, out, found := generateOne(t, "t.go", []byte(in), toSet([]string{"Root"}))
	if !found["Root"] || found["Log"] || found["Tun"] || found["Other"] {
		t.Fatalf("found = %#v", found)
	}
	got := string(out)
	if strings.Contains(got, "func (Log)") || strings.Contains(got, "func (Tun)") {
		t.Fatalf("generated methods for child types:\n%s", got)
	}
	for _, want := range []string{
		`"log":`,
		`Desc: "logging"`,
		`"log.file"`,
		`Desc: "path to log"`,
		`"tunnels":`,
		`"tunnels[].name"`,
		`Desc: "tunnel id"`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("missing %s in:\n%s", want, got)
		}
	}
	if strings.Contains(got, `"x"`) {
		t.Fatalf("unrelated type leaked into map:\n%s", got)
	}
}

func TestGenerateLeadingDoc(t *testing.T) {
	in := `package p

type S struct {
	// desc=Insecure skips TLS certificate verification.
	Insecure bool ` + tag(`toml:"insecure"`) + `
}
`
	_, out, _ := generateOne(t, "t.go", []byte(in), toSet([]string{"S"}))
	if !strings.Contains(string(out), `Desc: "Insecure skips TLS certificate verification."`) {
		t.Fatalf("missing doc comment:\n%s", out)
	}
}

func TestGenerateMultilineDesc(t *testing.T) {
	in := `package p

type S struct {
	// desc=TrustPEM is the path to the trust bundle.
	// In client mode, this is used to validate the server certificate.
	TrustPEM string ` + tag(`toml:"trust_pem"`) + `
}
`
	_, out, _ := generateOne(t, "t.go", []byte(in), toSet([]string{"S"}))
	want := `Desc: "TrustPEM is the path to the trust bundle. In client mode, this is used to validate the server certificate."`
	if !strings.Contains(string(out), want) {
		t.Fatalf("missing joined doc:\n%s", out)
	}
}

func TestGenerateDirectives(t *testing.T) {
	in := `package p

type S struct {
	// default=DefaultMTU
	// optional=true
	// desc=Maximum Transmission Unit.
	MTU int ` + tag(`toml:"mtu"`) + `
}
`
	_, out, _ := generateOne(t, "t.go", []byte(in), toSet([]string{"S"}))
	got := string(out)
	if !strings.Contains(got, `Default: fmt.Sprint(DefaultMTU)`) {
		t.Fatalf("default expression not copied:\n%s", got)
	}
	if !strings.Contains(got, `Optional: true`) {
		t.Fatalf("missing optional:\n%s", got)
	}
	if !strings.Contains(got, `Desc: "Maximum Transmission Unit."`) {
		t.Fatalf("missing desc:\n%s", got)
	}
	if !strings.Contains(got, `"fmt"`) {
		t.Fatalf("expected fmt import:\n%s", got)
	}
}

func TestGenerateQuoteEscaping(t *testing.T) {
	in := `package p

type S struct {
	// desc=say "hello"
	Name string ` + tag(`json:"name"`) + `
}
`
	_, out, _ := generateOne(t, "t.go", []byte(in), toSet([]string{"S"}))
	if !strings.Contains(string(out), `Desc: "say \"hello\""`) {
		t.Fatalf("missing escaped quotes:\n%s", out)
	}
}

func TestGenerateTrailingIgnored(t *testing.T) {
	in := `package p

type S struct {
	// desc=leading wins
	Name string ` + tag(`toml:"name"`) + ` // trailing is ignored
}
`
	_, out, _ := generateOne(t, "t.go", []byte(in), toSet([]string{"S"}))
	got := string(out)
	if !strings.Contains(got, `Desc: "leading wins"`) {
		t.Fatalf("expected leading desc:\n%s", got)
	}
	if strings.Contains(got, "trailing") {
		t.Fatalf("trailing comment should be ignored:\n%s", got)
	}
}

func TestGenerateNoCommentEmptyMap(t *testing.T) {
	in := `package p

type S struct {
	Port int ` + tag(`toml:"port"`) + `
}
`
	_, out, found := generateOne(t, "t.go", []byte(in), toSet([]string{"S"}))
	if !found["S"] {
		t.Fatal("expected S to be found")
	}
	if !strings.Contains(string(out), "map[string]common.FieldMeta") {
		t.Fatalf("expected FieldMeta map:\n%s", out)
	}
	if strings.Contains(string(out), `"port"`) {
		t.Fatalf("uncommented field should be omitted:\n%s", out)
	}
}

func TestGenerateUnknownKey(t *testing.T) {
	in := `package p

type S struct {
	// enum=a,b
	// desc=nope
	Name string ` + tag(`toml:"name"`) + `
}
`
	_, _, err := generate("t.go", []byte(in), toSet([]string{"S"}))
	if err == nil || !strings.Contains(err.Error(), "unknown") {
		t.Fatalf("error = %v, want unknown key", err)
	}
}

func TestGenerateInvalidOptional(t *testing.T) {
	in := `package p

type S struct {
	// optional=maybe
	Name string ` + tag(`toml:"name"`) + `
}
`
	_, _, err := generate("t.go", []byte(in), toSet([]string{"S"}))
	if err == nil || !strings.Contains(err.Error(), "optional=") {
		t.Fatalf("error = %v, want invalid optional", err)
	}
}

func TestGenerateInvalidDefaultExpr(t *testing.T) {
	in := `package p

type S struct {
	// default=.
	Name string ` + tag(`toml:"name"`) + `
}
`
	_, _, err := generate("t.go", []byte(in), toSet([]string{"S"}))
	if err == nil || !strings.Contains(err.Error(), "default=") {
		t.Fatalf("error = %v, want invalid default expression", err)
	}
}

func TestGenerateBareCommentError(t *testing.T) {
	in := `package p

type S struct {
	// Tunnel identifier
	Name string ` + tag(`toml:"name"`) + `
}
`
	_, _, err := generate("t.go", []byte(in), toSet([]string{"S"}))
	if err == nil || !strings.Contains(err.Error(), "expected default=") {
		t.Fatalf("error = %v, want expected directive", err)
	}
}

func TestGenerateMultipleTypes(t *testing.T) {
	in := `package p

type A struct {
	// desc=from A
	X int ` + tag(`toml:"x"`) + `
}

type B struct {
	// desc=from B
	X int ` + tag(`toml:"x"`) + `
}
`
	files, found, err := generate("t.go", []byte(in), toSet([]string{"A", "B"}))
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if !found["A"] || !found["B"] {
		t.Fatalf("found = %#v", found)
	}
	if len(files) != 2 {
		t.Fatalf("got %d files, want 2", len(files))
	}
	byName := map[string]string{}
	for _, f := range files {
		byName[filepath.Base(f.path)] = string(f.data)
	}
	if !strings.Contains(byName["zfielddocs_A.go"], "func (A) DescribeFields()") {
		t.Fatal("missing A method")
	}
	if !strings.Contains(byName["zfielddocs_B.go"], "func (B) DescribeFields()") {
		t.Fatal("missing B method")
	}
}

func TestGenerateIdempotent(t *testing.T) {
	in := `package p

type S struct {
	// desc=Tunnel identifier
	Name string ` + tag(`toml:"name"`) + `
}
`
	allow := toSet([]string{"S"})
	_, first, _ := generateOne(t, "t.go", []byte(in), allow)
	_, second, _ := generateOne(t, "t.go", []byte(in), allow)
	if string(first) != string(second) {
		t.Fatalf("non-idempotent\nfirst:\n%s\nsecond:\n%s", first, second)
	}
}

func TestProcessFilesMissingType(t *testing.T) {
	dir := t.TempDir()
	src := filepath.Join(dir, "t.go")
	if err := os.WriteFile(src, []byte("package p\n\ntype S struct { X int }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := processFiles([]string{"S", "Missing"}, []string{src})
	if err == nil || !strings.Contains(err.Error(), "Missing") {
		t.Fatalf("error = %v, want missing type", err)
	}
}

func TestOutputPath(t *testing.T) {
	got := outputPath("pkg/config/config.go", "Config")
	if !strings.HasSuffix(got, "zfielddocs_Config.go") {
		t.Fatalf("outputPath = %q", got)
	}
}

func TestShouldSkip(t *testing.T) {
	if !shouldSkip("zfielddocs_Config.go") {
		t.Fatal("expected zfielddocs_Config.go to be skipped")
	}
	if !shouldSkip("walker_test.go") {
		t.Fatal("expected _test.go to be skipped")
	}
	if shouldSkip("config.go") {
		t.Fatal("did not expect config.go to be skipped")
	}
}

func TestParseArgs(t *testing.T) {
	typeList, files, err := parseArgs([]string{"-type", "Config,LogConfig", "config.go"})
	if err != nil {
		t.Fatal(err)
	}
	if typeList != "Config,LogConfig" {
		t.Fatalf("typeList = %q", typeList)
	}
	if len(files) != 1 || files[0] != "config.go" {
		t.Fatalf("files = %#v", files)
	}
	if got := splitTypes(typeList); len(got) != 2 || got[0] != "Config" || got[1] != "LogConfig" {
		t.Fatalf("splitTypes = %#v", got)
	}
}

func tag(s string) string {
	return "`" + s + "`"
}

func formatted(t *testing.T, s string) string {
	t.Helper()
	out, err := format.Source([]byte(s))
	if err != nil {
		t.Fatalf("format: %v\n%s", err, s)
	}
	return string(out)
}
